query: |
  SELECT * FROM Equipment

input_file: Equipment.xlsx
#output_file: Equipment
#csv: True
#xlsx: True
#json: False
#xml: False

#db:
#  type: mssql #mssql, pg
#  database: IntegrationDB_BFG_TEST
#  database_server: rk-dax-sql-dev
#  database_port: 1433
#  database_login: bfg-int-local
#  database_password: RjkjybzGferjd888

output_db:
  type: mssql # mssql, pg
  database: IntegrationDB_BFG_TEST
  database_server: rk-dax-sql-dev
  database_port: 1433
  database_login: bfg-int-local
  database_password: RjkjybzGferjd888
  table: test
  replace: replace # replace -- заменить, append -- дописать
